version: 0.2

phases:
  install:
    commands:
      - pip install boto3
      - aws cloudformation package --template-file sample-sam.yaml --s3-bucket serverless-app-src-th13 --output-template-file sample-sam-output.yml
artifacts:
  type: zip
  files:
    - sample-sam-output.yml
